name: manage-azure-policy-35d201d3
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Policies/policies/Require_a_tag_on_resource_groups-(Modified)_13a3970a-a170-40cb-9904-83a99561cc57/**'
#      - .github/workflows/manage-azure-policy-35d201d3.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_35d201d3}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Policies/policies/Require_a_tag_on_resource_groups-(Modified)_13a3970a-a170-40cb-9904-83a99561cc57/**
